use_frameworks!

platform :ios, '11.0'

target 'Example' do
  pod 'GKPopupController', :path => '../'

  pod 'GKNavigationBar'
  pod 'GKVideoScrollView'
  pod 'ZFPlayer/AVPlayer'
  pod 'SDWebImage'
  pod 'Masonry'
end

post_install do |installer|
  # 消除版本警告
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      excluded_archs = config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]']
      excluded_archs = excluded_archs.nil? ? '' : excluded_archs
      if !excluded_archs.include?('arm64')
        excluded_archs = "#{excluded_archs} arm64"
      end
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = excluded_archs
    end
  end
end
